name: audio_lib
version: 0.0.1
description: >-
  A super simple example of calling C code from Dart with FFI

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.7.0 <5.0.0"

dependencies:
  ffigen: ^7.2.11
  path: ^1.8.3


dependency_overrides:
  lints: ^2.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  # test_utils depends on code elsewhere in the samples repository.
  # You can reference it for useful cross-platform testing functionality
  # or remove it if you want to use this example standalone.
  #test_utils:
    #path: ../test_utils